# Generated by Django 2.0.7 on 2018-10-02 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('ext', models.CharField(max_length=5)),
                ('object_html', models.TextField(editable=False)),
                ('is_root', models.BooleanField(default=False, editable=False)),
                ('par_fldr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_objects', to='myfiles.DirObject')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myfiles_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='dirobject',
            unique_together={('par_fldr', 'name', 'ext')},
        ),
    ]
