# Generated by Django 2.0.7 on 2018-10-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0002_auto_20181002_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='dirobject',
            name='special',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
