# Generated by Django 2.0.7 on 2018-10-19 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0003_dirobject_special'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dirobject',
            options={'ordering': ['name']},
        ),
    ]
