# Generated by Django 2.0.7 on 2018-10-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0004_auto_20181019_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='dirobject',
            name='sort_type',
            field=models.CharField(default='name', max_length=8),
        ),
    ]
