# Generated by Django 2.0.7 on 2018-10-25 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0005_dirobject_sort_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dirobject',
            name='par_fldr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_objects', to='myfiles.DirObject'),
        ),
    ]
