# Generated by Django 2.0.7 on 2018-10-25 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0007_auto_20181025_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='dirobject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dirobject',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
