# Generated by Django 2.0.7 on 2018-10-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0008_auto_20181025_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dirobject',
            old_name='last_modified',
            new_name='modified',
        ),
        migrations.RemoveField(
            model_name='dirobject',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='dirobject',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
