# Generated by Django 2.0.7 on 2018-10-31 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0009_auto_20181026_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='dirobject',
            name='temp_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
