# Generated by Django 2.0.7 on 2018-11-15 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0012_auto_20181115_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='last_continue',
            new_name='last_continued',
        ),
    ]
