# Generated by Django 2.0.7 on 2018-11-16 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0013_auto_20181115_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-modified']},
        ),
        migrations.RenameField(
            model_name='session',
            old_name='last_update',
            new_name='modified',
        ),
    ]
