# Generated by Django 2.0.7 on 2018-11-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0014_auto_20181116_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dirobject',
            name='special',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
